---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-helloworld-deployment
spec:
  selector:
    matchLabels:
      app: nginx-helloworld
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - name: nginx-helloworld
        image: swr.ap-southeast-3.myhuaweicloud.com/batch/docker-nginx-hello-world:<BUILD_TAG>
        ports:
        - containerPort: 80
