apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-nginx-hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-helloworld
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - image: swr.cn-east-3.myhuaweicloud.com/batch/docker-nginx-hello-world:<BUILD_TAG>
        ports:
           containerPort: 80
        imagePullPolicy: IfNotPresent
        command:
          - sleep
        args:
          - '1000'
        name: nginx-helloworld
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
